### ISSUE TITLE
当前脚本一直编译失败

### ISSUE THREAD

**Issue by scutDavid** [puerts/backend-v8#12]
自己fork了最新的master分支 然后启用流水线编译一直失败，
https://github.com/scutDavid/backend-v8/actions/runs/7634789178/job/20799200511，车神有空能帮忙看下么 对github的流水线以及v8的编译不是很熟悉。

**Comment by chexiongsheng** [comment]
我估计是github上的镜像变了，报错的地方是D:/a/backend-v8/backend-v8/v8/v8/build/toolchain/win/setup_toolchain.py，工具栏安装脚本

**Comment by scutDavid** [comment]
那得怎么修改到正确的镜像地址呢 一开始我还以为是虚拟环境里Python路径的问题。

**Comment by chexiongsheng** [comment]
镜像指的是虚拟机的镜像，是github决定的，不过我看同样是window，也有编译成功的，也是同样的镜像，奇怪

**Comment by chexiongsheng** [comment]
mac那个报错倒是python脚本的问题

**Comment by scutDavid** [comment]
> 镜像指的是虚拟机的镜像，是github决定的，不过我看同样是window，也有编译成功的，也是同样的镜像，奇怪

实际上 windows 拷贝头文件的那几个也是不成功的 编译没成功 报错也是一样的

**Comment by scutDavid** [comment]
![image](https://github.com/puerts/backend-v8/assets/30872025/e1829663-c349-4b9b-ab43-a2448c96b56f)

**Comment by chexiongsheng** [comment]
window看上去也和镜像上的python升级有关。
可以试试用depot_tools里头的python，在path那加在前面就可以了，可以参考linux这里：https://github.com/scutDavid/backend-v8/blob/master/linux.sh#L11

**Comment by scutDavid** [comment]
好的 我试下
